### ISSUE TITLE
Preserve custom init_containers

### ISSUE THREAD

**Issue by g-braeunlich** [gesiscss/persistent_binderhub#17]
Would it be possible to not override `self.init_containers` but only add the `project-manager` init container in [persistent_bhub_config.py](persistent_binderhub/files/jupyterhub/persistent_bhub_config.py)?
E.g.

```python
if not any(ic["name"] == "project-manager" for ic in self.init_containers):
    self.init_containers.append({
            "name": "project-manager",
            "image": self.image,
            "command": command,
            # volumes is already defined for notebook container (self.volumes)
            "volume_mounts": [projects_volume_mount],
        })
```

**Comment by MridulS** [comment]
That sounds okay to me, but it would be nice to know/document an example how else is initContainer is being used :)

**Comment by g-braeunlich** [comment]
In my case: I want to automatically do
```
git config --global user.name ...
git config --global user.email ...
```
Therefore I would like to subclass `PersistentBinderSpawner` and add another init container doing that.
I cannot wrap `start()` and add it afterwards, because at the end of `start()` the spawning will start.

**Comment by MridulS** [comment]
@g-braeunlich  https://github.com/jupyterhub/binderhub/pull/1081 looks related?

**Comment by g-braeunlich** [comment]
Yes but in my case, I dont want to modify the image. I want to modify the users persisted volume
