### ISSUE TITLE
font files of binder are not found

### ISSUE THREAD

**Issue by bitnik** [gesiscss/persistent_binderhub#2]
this chart by default configures binder to run at `/services/binder/`. but font files of binder are always served  at `/`, this is already a known issue, https://github.com/jupyterhub/binderhub/issues/793.

**Comment by bitnik** [comment]
this is fixed with https://github.com/jupyterhub/binderhub/pull/1247, so this issue can be closed when BinderHub chart dependency is upgraded. I just wanted to note it here :)

**Comment by MridulS** [comment]
Thanks for the heads up 🥳

**Comment by arnim** [comment]
Thank you @bitnik 👍

**Comment by MridulS** [comment]
Need to make a new release with the updated binderhub chart.

**Comment by MridulS** [comment]
released in https://github.com/gesiscss/persistent_binderhub/releases/tag/0.2.0-n528
