### ISSUE TITLE
Failed to connect to event stream

### ISSUE THREAD

**Issue by FasihZafar** [gesiscss/persistent_binderhub#27]
Hi, I'm facing this error every time i try to launch a repo.  Any ideas how to debug  and solve this Thanks.
![image](https://user-images.githubusercontent.com/44728933/178325429-ce208a57-c219-47df-9588-62c180f01043.png)

**Comment by arnim** [comment]
Thank you for reporting this @FasihZafar 

"Failed to connect to event stream" could happen from time to time (just as in a regular binder) but not every time.
Have you tried a different repository to launch, e.g. https://github.com/binder-examples/requirements

We are currently collecting ideas on how to improve the dynamic image building for JHub ... so your feedback is very welcome ;)

2i2c-org/infrastructure/issues/1382

**Comment by arnim** [comment]
Are you running on minikube?

**Comment by FasihZafar** [comment]
Hey arnim. I'm trying to run it on gke. This occurred because i forgot to update the dummy hub_url. Thanks
