### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by FasihZafar** [gesiscss/persistent_binderhub#31]
I've deployed the pbhub on gke following the readme. I created two dummy users the following error occurs when the second user launches the same project.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/44728933/192648105-078c1a71-3e9a-4807-9f22-3d708216434b.png">

**Comment by arnim** [comment]
As mentioned we are [currently developing](https://github.com/gesiscss/persistent_binderhub/issues/27#issuecomment-1180710514) a replacement for this system. I hope that we can address such issues better with the new implementation. Have you tried to run standard JHub on gke to rule out any other network issues?

**Comment by arnim** [comment]
Did you get it to work on minikube?

**Comment by FasihZafar** [comment]
Hi @arnim I can definitely try out both the suggestions and can share an update.

**Comment by FasihZafar** [comment]
Hi @arnim I've tried setting up on minikube but I'm running into the  "Failed to connect to the event stream" erorr

**Comment by arnim** [comment]
Also for standard JHub on minikube?

**Comment by FasihZafar** [comment]
This occurred due to one of the security plugins from my company which blocked the requests to WebSockets. Thanks for the help.
