### ISSUE TITLE
Dockerfile repos

### ISSUE THREAD

**Issue by bitnik** [gesiscss/persistent_binderhub#4]
Following kinds of Dockerfiles are not supported:

- [ ] with username different than `jovyan`
~- [x] which doesnt install jupyterhub, e.g. https://github.com/microsoft/QuantumKatas~

We should support them and until then we should at least show warnings in the UI.

**Comment by MridulS** [comment]
For the repos which don't install jupyterhub we shouldn't be trying to fix that, hub is required to run authenticated binder and installing hub is now part of the documentation[1] if users want to create a custom docker file which runs in authenticated as well as unauthenticated binderhubs.

[1] https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html?highlight=docker#preparing-your-dockerfile

**Comment by arnim** [comment]
Don't see there any hard "requirement" to have `NB_USER=jovyan`

**Comment by arnim** [comment]
Where is it documented that NB_USER=!jovyan won't persist?

**Comment by MridulS** [comment]
The above comment was for the second type of dockerfiles (no jupyterhub installed).
